#!/sbin/busybox sh

export BOOTREC_EVENT_NODE="/dev/input/event7 c 13 71"
export BOOTREC_EVENT="/dev/input/event7"
export BOOTREC_LED_RED="/sys/class/leds/pwr-red/brightness"
export BOOTREC_LED_GREEN="/sys/class/leds/pwr-green/brightness"
export BOOTREC_LED_BLUE="/sys/class/leds/pwr-blue/brightness"
export BOOTREC_FOTA_NODE="/dev/block/mmcblk0p11 b 179 11"
export BOOTREC_FOTA="/dev/block/mmcblk0p11"
